### ISSUE TITLE
Logs show: "The user aborted a request"

### ISSUE THREAD

**Issue by ChristianMurphy** [ChristianMurphy/lerna-webjar#2]
This does not cause the release to fail, the release process continues, but still a strange message to see.
 
```
{ AbortError: The user aborted a request.
    at abort (~/notification-web-components/node_modules/node-fetch/lib/index.js:1401:16)
    at AbortSignal.abortAndFinalize (~/notification-web-components/node_modules/node-fetch/lib/index.js:1416:4)
    at AbortSignal.dispatchEvent (~/notification-web-components/node_modules/event-target-shim/dist/event-target-shim.js:818:35)
    at abortSignal (~/notification-web-components/node_modules/abort-controller/dist/abort-controller.js:52:12)
    at AbortController.abort (~/notification-web-components/node_modules/abort-controller/dist/abort-controller.js:91:9)
    at delay.then (~/notification-web-components/node_modules/ky/umd.js:128:20) type: 'aborted', message: 'The user aborted a request.' }
```

**Comment by ChristianMurphy** [comment]
this was related to a timeout, resolved in version 1.1.1
